version: '3.7'
services:
  ioc:
    image: lnlscon/cons-topcon:devel-v1.0
    command: sleep infinity
    build: .
    hostname: ioc
    environment:
      - CMD=st-test.cmd
    volumes:
      - "./TopConApp/Db/:/opt/cons-topcon/db:rw"
      - "./socket/:/var/run/reg/:rw"

