version: '3.7'
services:
  dipoles:
    image: lnlscon/cons-topcon:dipoles-v1.0
    build:
        context: .
        dockerfile: Dockerfile
        target: dipoles

  quadrupoles:
    image: lnlscon/cons-topcon:quadrupoles-v1.0
    build:
        context: .
        dockerfile: Dockerfile
        target: quadrupoles

  sextupoles:
    image: lnlscon/cons-topcon:sextupoles-v1.0
    build:
        context: .
        dockerfile: Dockerfile
        target: sextupoles

